name: CI

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        pyversion: ['3.8', '3.9', '3.10', '3.11']

    steps:
      - uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.pyversion }}

      - name: Cache pip
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip # This path is specific to Ubuntu
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install pip requirements
        run: |
          pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          pip install --upgrade -r requirements_dev.txt
      
      - name: Install APT requirements
        run: |
          sudo apt-get install texlive-latex-recommended texlive-latex-extra dvipng cm-super

      - name: Run flake8
        run: flake8 hidden_context tests
        if: ${{ always() }}

      - name: Run black
        run: black --check hidden_context tests
        if: ${{ always() }}

      - name: Run isort
        run: isort --check --diff hidden_context tests
        if: ${{ always() }}

      - name: Check types
        if: ${{ always() }}
        run: |
          mypy hidden_context tests
      
      - name: Run tests
        if: ${{ always() }}
        timeout-minutes: 10
        run: |
          pytest -m "not uses_huggingface" --log-cli-level=INFO
